const SCALES = [
  ['C', 'D', 'E', 'F', 'G', 'A', 'B'],
  ['F', 'G', 'A', 'Bb', 'C', 'D', 'E'],
  ['Bb', 'C', 'D', 'Eb', 'F', 'G', 'A'],
  ['Eb', 'F', 'G', 'Ab', 'Bb', 'C', 'D'],
  ['Ab', 'Bb', 'C', 'Db', 'Eb', 'F', 'G'],
  ['Db', 'Eb', 'F', 'Gb', 'Ab', 'Bb', 'C'],
  ['Gb', 'Ab', 'Bb', 'Cb', 'Db', 'Eb', 'F'],

  ['G', 'A', 'B', 'C', 'D', 'E', 'F#'],
  ['D', 'E', 'F#', 'G', 'A', 'B', 'C#'],
  ['A', 'B', 'C#', 'D', 'E', 'F#', 'G#'],
  ['E', 'F#', 'G#', 'A', 'B', 'C#', 'D#'],
  ['B', 'C#', 'D#', 'E', 'F#', 'G#', 'A#'],
  ['F#', 'G#', 'A#', 'B', 'C#', 'D#', 'E#'],
];

export const PROGRESSIONS = [
  {
    label: 'Major 2-5-1',
    chords: ['D-7 G7 ', 'C^7   '],
  },
  {
    label: 'Minor 2-5-1',
    chords: ['D-7b5 G7b9b13 ', 'C-7   '],
  },
  {
    label: 'Major 5-1',
    chords: ['G7   ', 'C^7   '],
  },
  {
    label: 'Minor 5-1',
    chords: ['G7b9b13   ', 'C-7   '],
  },
];

function pickRandom(array) {
  return array[Math.floor(Math.random() * array.length)];
}

function transposeToRandom(progression) {
  const scale = pickRandom(SCALES);
  return progression.map(measure => transposeMeasure(measure, scale));
}

function transposeMeasure(measure, scale) {
  const parts = measure.split(/([ |])/);
  return parts.map(part => part.slice(0, 1).match('[A-G]') ? transposeChord(part, scale) : part).join('');
}

function transposeChord(chord, scale) {
  const root = chord.charAt(0);
  const index = SCALES[0].indexOf(root);
  return scale[index] + chord.slice(1);
}

function getRandomProgression(progressions) {
  const progression = pickRandom(progressions);
  return transposeToRandom(progression.chords);
}

export function downloadChart(progressions) {
  const title = 'Chord Practice';
  const author = 'Generated by random-chord-generator';
  const style = 'Medium Swing';
  const key = 'C';
  const unused = 'n';

  const rawChords = [];
  while (rawChords.length < 40) {
    rawChords.push(...getRandomProgression(progressions));
  }

  const chords = '[T44' + rawChords.map(chord => chord).join('|') + '|';
  const url = 'irealbook://' + [title, author, style, key, unused, chords].join('=');
  console.info(url);
  window.location.href = url;
}